[versions]
agp = "8.13.1"
kotlin = "2.2.21"
compose = "1.9.3"
androidx-activity-compose = "1.11.0"
androidx-test-ext = "1.3.0"
androidx-test-runner = "1.7.0"
androidx-test-core = "1.7.0"
androidx-lifecycle = "2.9.4"
kotlinx-coroutines = "1.10.2"

androidMinSdk = "26"
androidCompileSdk = "36"
androidTargetSdk = "36"
vanniktechMavenPublish = "0.35.0"

[libraries]
androidxTestExt = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidxTestRunner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidxTestCore = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidxLifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidxLifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidxLifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinxCoroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
